### ISSUE TITLE
Too slow when "Ensuring external files"

### ISSUE THREAD

**Issue by hieuft** [T-Dynamos/materialyoucolor-pyhton#15]
Hi, currently I'm having problems installing "python-materialyoucolor-git" from "aur yay".
When I run the command:
```
yay -S python-materialyoucolor-git
```
It takes too long to: "Ensuring external files", about 10 minutes for a file of only about 30kb.
The picture below is when I run the command above and it is loading the file into `./materialyoucolor/quantize/...`

![image](https://github.com/T-Dynamos/materialyoucolor-python/assets/138310839/0ae18903-81e4-4cb6-8155-e95f85d210ec)

**Comment by hieuft** [comment]
@T-Dynamos can you help me, please?

**Comment by T-Dynamos** [comment]
Fast solution: `sudo pip3 install --break-system-packages materialyoucolor`.

(No need to install from aur)
