### ISSUE TITLE
EM_X86_64 (62) instead of EM_AARCH64 (183)

### ISSUE THREAD

**Issue by herbe13** [T-Dynamos/materialyoucolor-pyhton#5]
Hi, I have this problem:

`/site-packages/materialyoucolor/quantize/celebi.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)`

It appears when I want to open the app and I honestly don't know how to fix it. Please help?

**Comment by T-Dynamos** [comment]
You need to use recipe to build it which is waiting to be merged here https://github.com/kivy/python-for-android/pull/2950. To build it now you should clone that fork and specify in `p4a.source_dir` and clean build.

**Comment by nastiliano** [comment]
Hello everybody.

First of all, thank you for this great project.

I've been reading too about create my own recipe, but honestly, I think it's hard to do it or I don't understand exactly how to do it...

I'm using last version of "kivymd" and I have the same problem...

My question would be, will be there a solution soon or I must do my own recipe yes or yes??

Thank you very much, best regards.

**Comment by herbe13** [comment]
@nastiliano in this moment, it is not known when the request made by T-Dynamos will be approved, but for now to solve it, do as he said above, clone the fork and set it to p4a.

**Comment by nastiliano** [comment]
Ok, ok...

But I'm following this guide but I'm a little bit lost:

https://buildozer.readthedocs.io/en/latest/contribute.html


For the moment I forked "python-for-android" to my github, I cloned this fork to my local PC project folder... and I don't know what more I must do...

Sorry...  I have to include some .sh script o something???

**Comment by T-Dynamos** [comment]
Now edit `buildozer.spec` find `p4a.source_dir` write there path of cloned forked p4a.

**Comment by FilipeMarch** [comment]
This is the procedure that worked for me for compiling `kivymd` with `materialyoucolor` (and fix OP issue):

folder structure:
```
.
├── buildozer.spec
├── p4a-recipes
│   └── materialyoucolor
│       ├── __init__.py
```
`p4a-recipes/materialyoucolor/__init__.py`
```python
from pythonforandroid.recipe import CompiledComponentsPythonRecipe


class MaterialyoucolorRecipe(CompiledComponentsPythonRecipe):
    need_stl_shared = True
    stl_lib_name = "c++_shared"
    version = "2.0.5"
    url = "https://github.com/T-Dynamos/materialyoucolor-pyhton/archive/refs/tags/v{version}.tar.gz"
    depends = ["setuptools"]
    call_hostpython_via_targetpython = False


recipe = MaterialyoucolorRecipe()
```
`buildozer.spec`
```spec
p4a.local_recipes = ./p4a-recipes
requirements = python3, kivy==2.3.0, https://github.com/kivymd/KivyMD/archive/master.zip, materialyoucolor, exceptiongroup, asyncgui, asynckivy, Pillow
```
commands:
```
buildozer android clean
buildozer -v android debug deploy run
```

successful result:
```
01-26 13:25:27.846 19803 19842 I python  : [INFO   ] [KivyMD      ] Color scheme generation. Get a color scheme from an installed palette - 0.01287499998579733 sec.
```

**Comment by nastiliano** [comment]
Mmmm.... I don't know why, but I have a lot of issues.

I've formatted my PC, reinstalled my Linux distro and I'll be waiting for the merged/aproved solution.

Thank you very much for help.

Best regards.

**Comment by nastiliano** [comment]
Hello @FilipeMarch 

Sorry for annoying you again, but your help was excellent for me.

Your solution it worked for some weeks but today (one day to another) doesn't work again.

The message error when debuggind in my device is:

" ImportError: cannot import name 'argb_from_rgba_01' from 'materialyoucolor.utils.color_utils' (/data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/materialyoucolor/utils/color_utils.pyc) "

Could you help me? Thank you very much.
Best regards.

PD: Maybe the recipe is already official and I can compile directly??

**Comment by T-Dynamos** [comment]
@nastiliano Just update the recipe version to `2.0.7`.

**Comment by nastiliano** [comment]
Ooopppss... sorry for my ignorance

It works again!

Thank you very much.
