### ISSUE TITLE
Why do I get errors when building android programs in buildozer?

### ISSUE THREAD

**Issue by lejlm233** [T-Dynamos/materialyoucolor-pyhton#6]
ImportError: dlopen failed: "/data/data/com.film.canary/files/app/_python_bundle/site-packages/materialyoucolor/quantize/celebi.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)

**Comment by arncode90** [comment]
follow this post by FilipeMarch
https://github.com/T-Dynamos/materialyoucolor-python/issues/5#issuecomment-1916063417
